### ISSUE TITLE
can not connected

### ISSUE THREAD

**Issue by haiyangxinxin** [pluosi/app-host#57]
Cannot render console from 172.17.0.1! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
   (0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by AppsController#index as */*
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."role" = ? LIMIT ?  [["role", "admin"], ["LIMIT", 1]]
Redirected to https://localhost:3000/users/new
Completed 302 Found in 16ms (ActiveRecord: 0.5ms)

Started GET "/" for 127.0.0.1 at 2019-05-18 09:35:34 +0000
Cannot render console from 10.0.230.136! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by AppsController#index as HTML
  User Exists (0.2ms)  SELECT  1 AS one FROM "users" WHERE "users"."deleted_at" IS NULL AND "users"."role" = ? LIMIT ?  [["role", "admin"], ["LIMIT", 1]]
Redirected to https://10.10.0.212:3000/users/new
Completed 302 Found in 2ms (ActiveRecord: 0.2ms)
### 
**using : http://10.10.0.212:3000 , it will redirected to https://10.10.0.212:3000**

what is wrong ?  
help me please !!!!!!!!!!

**Comment by iBcker** [comment]
Because ipa installation requires https, it is recommended that you use https, even if it is a self-signed certificate.
We recommend that you use nginx to proxy the requests to the rails service instead of directly by changing the ip form.

If you insist on accessing directly through 10.10.0.212, you can usually modify the configuration by https://stackoverflow.com/questions/29417328/how-to-disable-cannot-render-console-from-on-rails.
